### ISSUE TITLE
Configurable JDBC Realm

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-shiro#2]
Let's add support for setting up JDBCRealm](https://github.com/apache/shiro/blob/master/core/src/main/java/org/apache/shiro/realm/jdbc/JdbcRealm.java) , with properties loaded from configuration. It will be implemented as `JdbcRealmFactory` and will be configured as:

```yml
shiro:
  realms:
    r1: 
      type: jdbc
      datasource: ds1
      authenticationQuery: "SELECT ..."
```
