### ISSUE TITLE
Configurable ActiveDriectoryRealm

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-shiro#5]
Let's add support for setting up [ActiveDirectoryRealm](https://github.com/apache/shiro/blob/master/core/src/main/java/org/apache/shiro/realm/activedirectory/ActiveDirectoryRealm.java) , with properties loaded from configuration. It will be implemented as `ActiveDirectoryRealmFactory` and will be configured as:

```yaml
shiro:
  realms:
    r1: 
      type: activeDirectory
      url: ldap://my.example.org
```
