### ISSUE TITLE
shiroweb.urls does not support ordering of filters

### ISSUE THREAD

**Issue by atomashpolskiy** [bootique/bootique-shiro#7]
`shiroweb.urls` is a map, which means there's no way to hint Shiro in which order to perform path matching. This is effectively a show-stopper. Obvious fix would be to change this property to be a list. Or maybe some additional re-ordering of the key set can be done internally before filter mapping is passed to Shiro.

**Comment by andrus** [comment]
Good point. Somehow this has not popped up yet in the tests and early adopter projects. Will work on this.

**Comment by andrus** [comment]
Just realized that YAML maps are deserialized into LinkedHashMaps by Jackson. So the ordering of map iterators is stable. Also if there are no contributions from multiple sources, the ordering will match exactly the ordering in YAML.

**Comment by andrus** [comment]
Here is a possible scheme for explicit ordering (e.g. in override maps) using optional references to other entries:

```yaml
shiroweb:
  urls:
    # traditional default-ordered entry
    "/a/**" : anon
    # explicit relative ordering. Refers to a key from another YAML
    "/b/**" :
      chain: anon
      before: "/**"
```
